### ISSUE TITLE
Question: use along side regular library

### ISSUE THREAD

**Issue by adamfk** [enjoyneering/ESP8266-I2C-Driver#4]
Hello,

I'd like to try your implementation, but I don't want to replace the existing library files. Is that possible? Can I use it like a regular library?

Thanks,

Adam

**Comment by enjoyneering** [comment]
You can use it  like a regular library and you don't need to change anything in your sketches. However, if you need ESP8266 to work as a slave device you should stick with the original library. If this is not a problem, simply replace the files in the following directories:

- replace "**twi.h**", "**core_esp8266_si2c.c**" in folder %USERPROFILE%\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\X.X.X\cores\esp8266

where X.X.X is the version of the Arduino ESP8266 framework, for example 2.5.0

- replace "**Wire.h**", "**Wire.cpp**" in folder %USERPROFILE%\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\Wire

If you want to keep the original files - just change the file extension, "**twi.h.OLD**". Then you always can go back.

**Comment by adamfk** [comment]
Thanks.
