### ISSUE TITLE
What was wrong with the old one?

### ISSUE THREAD

**Issue by philbowles** [enjoyneering/ESP8266-I2C-Driver#5]
What exactly does this fix? What is/was problem with the stock library? What changes were made to overcome it. Why should I use THIS version?

I would have expected these questions to be addressed in the README....

**Comment by enjoyneering** [comment]
bacause of this:
 - [I2C hang with very slow I2C slave](https://github.com/esp8266/Arduino/issues/2162)
- [Reliable Startup for I2C Battery Backed RTC](http://www.forward.com.au/pfod/ArduinoProgramming/I2C_ClearBus/index.html)
