### ISSUE TITLE
Не совместимость с последней версией ядра

### ISSUE THREAD

**Issue by dzanis** [enjoyneering/ESP8266-I2C-Driver#6]
У меня проблемы с подкючением DS3231 на ESP-01 , в начале не хочет читать время,только позже и то надо вручную это делать через веб интерфейс,что не подходит,ведь надо после включения автоматом считать время.Попробовал ваш фикс I2C ,и сразу выскочило несколько ошибок,исправить недолго,не было difine TWI_BUFFER_LENGTH и методах twi_writeTo twi_readFrom аргументы менял на unsigned char .Но RTC DS3231 вообще не работал,даже вручную.Думаю может ошибка в загруженности ESP-01 в начале инициализации.Как думаете они уже пофиксили в официальном ядре I2C?

**Comment by enjoyneering** [comment]
"последней версией ядра" - это не версия, я такой не знаю. сам проверял на ядре 2.5.2 - никаких ошибок и конфликтов не было. менять надо ВСЕ файлы, старые УДАЛЯТЬ или переименовать **расширение**. если у старых просто поменять название то посыпятся ошибки. потому что линковщик работает с тем что внутри файлов *.h и *.cpp, а не с именами. это вам не windows. :)

у ESP-01 не выведены SDA - GPIO4 и SCL - GPIO5, а те что есть GPIO1 и GPIO3 заняты Serial куда постоянно валятся служебные сообщения и все то что вы оправляете командой Serial.print()

есть способ  переназначить Serial с GPIO1 и GPIO3 на GPIO15 и GPIO13, полностью освободив их для I2C:

`Serial.swap();  //remap serial pins GPIO1/D2/UART0TXD & GPIO3/D7/UART0RXD to GPIO15/UART0RTS & GPIO13/UART0CTS`

после этого скорее всего придется модифицировать библиотеку DS3231 тк стандартные пины для I2C GPIO4 и GPIO5, а не  как у вас GPIO1 и GPIO3. какой DS3231 вы пользуетесь? подтягивающие резисторы на SDA и SCL стоят?

на будущее - всегда указывайте версию ядра ESP, версию Arduino IDE, и автора библиотеки. я мысли читать не умею. :)

кстати [вы не первый](https://github.com/enjoyneering/ESP8266-I2C-Driver/issues/1), кто не внимательно читает read.me

**Comment by dzanis** [comment]
Да,а вот версию я не посмотрел что у меня не последняя  лол :) Версия ядра ESP  у меня 2.5.0  Arduino IDE 1.8.9
Да, не выведены GPIO4 и GPIO5,поэтому менял подключения
```
 //вместо rtc.begin(); пишем
Wire.begin(0, 2);
```
Т.е модифицировать библиотеку DS3231 не нужно,просто Wire.begin( sda, scl);
Решил проблему "в начале не хочет читать время" тем что делаю несколько опросов RTC, и тогда всё нормально.

**Comment by enjoyneering** [comment]
ок. имхо для I2C лучше использовать GPIO1 и GPIO3

```
Serial.swap(); //remap serial pins GPIO1/D2/UART0TXD & GPIO3/D7/UART0RXD to GPIO15/UART0RTS & GPIO13/UART0CTS
Wire.begin(1, 3); //SDA-GPIO1 & SCL-GPIO3
```

потому что GPIO0 и GPIO2 учавствуют в конфигурации чипа для загрузки с флешки. если вдруг slave прижмет GPIO0 и GPIO2 и вы захотите reboot esp8266 все может закончится печально.

> модифицировать библиотеку DS3231 не нужно,просто Wire.begin( sda, scl);

это я знаю, но иногда в *.begin() пихают инициализацию чипа, а либа ничего не знает о ваших GPIO0 и GPIO2. прежде чем  вставлять Wire.begin(0, 2) после или вместо rtc.begin() всегда надо проверять что там автор накрутил. 

вы так и не сказали какую библиотеку DS3231 используете? заработал ли у вас мой драйвер?

> Решил проблему "в начале не хочет читать время" тем что делаю несколько опросов RTC, и тогда всё нормально.

это не решение. это костыль. так делать нельзя, надо разбираться. иначе в будушем такое отношение - тяп ляп и в продакшен, выйдет вам боком.

**Comment by dzanis** [comment]
Вот сериал мне как раз таки был нужен,для дебага.Сейчас его переделывать,сложно,на плате стоит не у меня.Библиотеку  для DS3231  брал от сюда  https://github.com/adafruit/RTClib
Драйвер не заработал,вообще не читало время, но это понятно,т.к версия ядра другая,как уже писал выше.Но позже думаю обновить ядро и попробывать ваш драйвер.Да надо разбираться,но у меня нету логического анализатора,и как без него разбираться в том чего не видно.Вот только методом проб удалось добиться решения,хоть и костыльное оно. Сейчас уже то устройство запаяно,работает у друга дома,забирать я его не буду.Надо новое собирать,и если настрою с вашим драёвером,то просто обновлю еспешки.

**Comment by enjoyneering** [comment]
да вы правы. модифицировать библиотеку не надо. вот код begin. 
```
boolean RTC_DS3231::begin(void) {
  Wire.begin();
  return true;
}
```
достаточно вместо rtc.begin(); написать Wire.begin(0, 2);
